project_id = "qayjpjwkcxqehbrkgunr"

[functions.ai-tools]
verify_jwt = false

[functions.manage-sources]
verify_jwt = false

[functions.fetch-news]
verify_jwt = false

[functions.radio-proxy]
verify_jwt = false
